Allow multiple packs images
StackStorm/stackstorm-ha pull request #166
Opened 2020-12-23 15:17 UTC by moonrail

Hello Maintainers,

this PR adds the option to use multiple st2 packs-images.

This is a breaking change, as value `st2.packs.image` is replaced by `st2.packs.images`. Datatype changes from dict/hash to list of dicts/hashes.

This is useful, when a lot of different packs are being used, as a single container can result in multiple GB very quickly, mostly due to virtualenvs.

When using multiple st2 pack-images, the User can reduce possible downtimes due to reduced image size of new/changed containers. Also the build process can be a lot faster, if the User is providing custom packs.

Currently there is a fail message implemented in `templates/deployments.yaml` to prevent Users from accidential removal of their custom st2packs-image. It triggers, when `st2.packs.image` is defined and not empty. This should notify all Users about this change.

In #118 & #160 a centralization of packs-specific definitions for this chart was shown. As these PRs are still being discussed for other reasons, I've decided to include these centralizations in this PR.
This should make these PRs a little smaller and more compatible to each other, once they will or will not be finalized.

2021-01-25 20:09 UTC, moonrail commented
Rebased to current master, should now be mergeable again :)

2021-02-25 19:44 UTC, armab requested changes
Thanks for PR! :+1:  Considering its breaking change nature looks good to mix with the other major behavior changes PRs.

Can you please sync the PR with the `master` one more time?

2021-02-25 19:49 UTC, armab commented on templates/deployments.yaml
> +{{- fail "Value st2.packs.image was renamed to st2.packs.images and is now a list of images" }}
Nice idea here! :+1:

2021-03-08 18:30 UTC, moonrail commented
Hey @armab 
Finally rebased and tested it again - should be mergable again :)

2021-03-13 20:04 UTC, armab approved these changes
Looks good!

Thanks a lot for contributing these changes! :+1:

2021-03-13 20:05 UTC, merged