Issue 188: st2rulesengine references datastore_crypto_key incorrectly
StackStorm/stackstorm-ha pull request #190
Opened 2021-03-26 14:35 UTC by lordpengwin

I fixed the secret name for the rules engine

2021-03-28 21:15 UTC, armab requested changes
Looks good! Thanks for the contribution :+1: 

Could you also include a respective Changelog record for this PR?

2021-03-29 11:57 UTC, lordpengwin commented
> Could you also include a respective Changelog record for this PR?

I'd be happy to but I'm not sure what you mean. Can you point me to an example of what you want?

2021-03-29 12:03 UTC, armab commented on CHANGELOG.md
> +* Fixed datastore_crypto_key secret name for rules engine (#188) (by @lordpengwin)
:+1:

2021-03-29 12:03 UTC, lordpengwin commented on CHANGELOG.md
> +* Fixed datastore_crypto_key secret name for rules engine (#188) (by @lordpengwin)
I figured it out :)

2021-03-29 12:04 UTC, armab approved these changes
Thanks for catching the bug and for the fix! :+1:

2021-03-29 12:16 UTC, merged